= Weimarnetz Registrator Getting Started Guide
  Andreas Bräu;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[introduction]
= Introduction

Weimarnetz Registrator is a RESTful microservice for managing node number in our network. See https://wireless.subsignal.org/index.php?title=IP-System for more details.

[[overview]]
= Overview

[[overview-http-verbs]]
== HTTP verbs
Weimarnetz Registrator tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs. To also support simple solutions like wget we wrap some verbs in GET requests.
|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PUT`
| Used to update an existing resource, full updates only

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
== HTTP status codes
Weimarnetz Registrator tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| Standard response for successful HTTP requests.
| The actual response will depend on the request method used.
| In a GET request, the response will contain an entity corresponding to the requested resource.
| In a POST request, the response will contain an entity describing or containing the result of the action.

| `201 Created`
| The request has been fulfilled and resulted in a new resource being created.

| `303 See other`
|

| `400 Bad Request`
| The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

| `401 Unauthorized`
|

| `404 Not Found`
| The requested resource could not be found but may be available again in the future. Subsequent requests by the client are permissible.
|===

[[resources]]
= Resources


[[resources-time]]
== Time
Just returns the current server time.

operation::time[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-querynode]]
== Node
The Node resource is used to get a Node.

operation::queryNodes[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-querynodes]]
== Nodes
The Nodes resource is used to get a list of Nodes.

operation::queryAllNodes[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-querynodeByMac]]
== Node by mac address
This resource is used to get a Node identified by a mac address.

operation::queryNodeByMac[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-addnode]]
== Add node
Adding a node returns the full node object

operation::addNode[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-addnodeviaget]]
== Add node via GET
Adding a node returns the full node object

operation::addNodeViaGet[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-updateode]]
== Add node with given node number
Adding a node returns the full node object

operation::addGivenNodeNumber[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-updateode]]
== Update node
Updating a node returns the full node object

operation::updateNode[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-updateodeviaget]]
== Update node via GET
Updating a node returns the full node object

operation::updateNodeViaGet[snippets='curl-request,http-request,http-response,response-body,response-fields']

[[resources-deletenode]]
== Delete a node

Delete a node from the database, needs authentication

operation::deleteNode[snippets='curl-request,http-request,http-response,response-body']

[[resources-dumpdatabase]]
== Dump complete database

Dumps the complete database, needs authentication

operation::dumpDatabase[snippets='curl-request,http-request,http-response,response-fields']

[[resources-importdatabase]]
== Import database

Imports the complete database, needs authentication.
Existing entries will be updated.

operation::importDatabase[snippets='curl-request,http-request,http-response,request-fields']