---
- name: "deploy everything"
  hosts: all
  become: yes
  become_method: sudo

  vars:
    - application_jar: '../target/registratorapp-1.0-SNAPSHOT.jar'
    - application_name: 'registratorapp'
    - jdk_version: 'zulu17-jdk'

  #roles:
    #- role: check_preconditions
    #- role: install_ansible
    #- role: install_java
    #- role: install_application

  roles:
    #- role: install_ansible
    - role: install_java
    #- role: install_netdata
    - role: install_application
